# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Simulateur de salaire DGAC
email: bruno.spyckerelle@aviation-civile.gouv.fr
description: > # this means to ignore newlines until "baseurl:"
  Simulateur de salaire pour les agents de la DGAC.
baseurl: "/simupaye" # the subpath of your site, e.g. /blog
url: "https://dgacfr.github.io" # the base hostname & protocol for your site
twitter_username: Bruno_Spy
github_username:  BrunoSpy

# Build settings
markdown: kramdown

sass:
  style: :compressed
