var fonctions = {
    "Première affectation": {
        "IEEAC affecté": 9
    },
    "BEA": {
        "Enquêteur en formation depuis plus d'un an": 10,
        "Assistant de subdivision": 11,
        "Enquêteur": 11,
        "Enquêteur senior": 12,
        "Enquêteur expérimenté": 13,
        "Adjoint au chef de division": 12,
        "Chef de division": 13,
        "Expert national labellisé": 13,
        "Expert international labellisé": 15,
        "Chef de département": 14,
        "Enquêteur expérimenté sénior": 14,
        "Adjoint au directeur": 15,
        "Secrétaire général": 15,
        "Directeur d'enquête": 15
    },
    "DTA": {
        "Chargé d'études": 10,
        "Chargé d'affaires": 11,
        "Chef de programme": 12,
        "Adjoint au chef de bureau": 12,
        "Chef de division (DTA/MCU)": 13,
        "Adjoint au chef de pôle Ciel Unique (DTA/MCU)": 13,
        "Chef de projet construction aéronautique (DTA/SDC)": 13,
        "Expert national labellisé": 13,
        "Expert international labellisé": 15,
        "Adjoint au chef de la MALGH": 14,
        "Chef de bureau": 14,        
        "Chef de pôle Ciel Unique (DTA/MCU)": 14,
        "Adjoint au sous-directeur": 15,
        "Adjoint au chef de mission": 15,
        "Directeur de cabinet": 15
    },
    "STAC": {
        "Chargé d'études": 10,
        "Assistant de subdivision": 11,
        "Chargé d'affaires": 11,
        "Chef de subdivision": 12,
        "Adjoint au chef de division": 12,
        "Chef de programme": 12,
        "Chef de division": 13,
        "Expert national labellisé": 13,
        "Expert international labellisé": 15,
        "Chef de département": 14
    },
    "SG": {
        "Chargé d'études": 10,
        "Chargé d'affaires": 11,
        "Chargé de projet": 11,    
        "Chef de programme": 12,
        "Adjoint au chef de bureau": 12,
        "Chef de bureau": 14,   
        "Conseiller mobilité carrière": 14,
        "Chef du SGTA": 15,
        "chargé de corps des IEEAC": 15,
        "Chef de mission": 15,
        "Directeur de cabinet": 15
    }
    "DSNA/EC": {
        "Assistant de subdivision": 10,
        "Chargé d'études": 10,
        "Chargé d'affaires": 11,
        "Chargé de projet": 11,
        "Chef de subdivision": 11,
        "Adjoint au chef de pôle": 12,
        "Chef de pôle": 13,
        "Chef de programme": 12,
        "Adjoint au chef de division": 12,
        "Adjoint au chef de département": 13,
        "Adjoint au chef de mission": 13,
        "Chef de division": 13,
        "Expert senior chargé d'un projet majeur": 13,
        "Expert national labellisé": 13,
        "Expert international labellisé": 15,
        "Chef de département": 14,
        "Directeur de programme": 15,
        "Chef de mission": 15,
        "Directeur de cabinet": 15
    },
    "DO/EC": {
        "Assistant de subdivision": 11,
        "Chargé de projet": 11,
        "Adjoint au chef de pôle": 12,
        "Chef de subdivision": 12,
        "Expert senior": 12,
        "Expert confirmé": 11,
        "Chef de programme": 12,
        "Chef de pôle": 13,
        "Adjoint au chef de division": 12,
        "Chef de division": 13,
        "Expert national labellisé": 13,
        "Expert international labellisé": 15,
        "Chef de département": 14,
        "Adjoint au chef de département": 13,
        "RSMI" : 14
    },
    "DTI": {
        "Expert": 10,
        "Expert confirmé": 11,
        "Expert senior": 12,
        "Chef de projet": 12,
        "Chargé de communication": 12,
        "Coordonnateur de site": 13,
        "Expert senior chargé d'un projet majeur": 13,
        "Expert national labellisé": 13,
        "Expert international labellisé": 15,
        "Chef du SMQS": 13,
        "Adjoint au chef de pôle":12,
        "Adjoint au chef du pôle consolidation des exigences opérationnelles": 13,
        "Adjoint au chef du pôle exigences systèmes et architecture": 13,
        "Adjoint au chef du pôle vol et information générale": 13,
        "Adjoint au chef du pôle outils du contrôleur et surveillance": 13,
        "Adjoint au chef du pôle communication vocale et liaisons de données air-sol": 13,
        "Adjoint au chef du pôle capteurs de surveillance": 13,
        "Adjoint au chef du pôle infrastructure de télécommunications et réseaux": 13,
        "Adjoint au chef du pôle intégration, validation et déploiement": 13,
        "Adjoint au chef du pôle équipements techniques communes": 13,
        "Adjoint au chef du pôle installations": 13,
        "Chef de pôle": 13,
        "Chef de pôle fréquences et servitudes": 13,
        "Chef du pôle consolidation des exigences opérationnelles": 14,
        "Chef du pôle exigences systèmes et architecture": 14,
        "Chef du pôle vol et information générale": 14,
        "Chef du pôle outils du contrôleur et surveillance": 14,
        "Chef du pôle communication vocale et liaisons de données air-sol": 14,
        "Chef du pôle capteurs de surveillance": 14,
        "Chef du pôle infrastructure de télécommunications et réseaux": 14,
        "Chef du pôle intégration, validation et déploiement": 14,
        "Chef du pôle équipements techniques communes": 14,
        "Chef du pôle installations": 14,
        "Conseiller du directeur": 14,
        "Adjoint au chef de domaine": 14,
        "Chef de département": 14,
        "Chef de domaine": 15
    },
    "SIA": {
        "Assistant de subdivision": 10,
        "Adjoint au chef de pôle": 11,
        "Chef de subdivision": 11,
        "Expert senior": 11,
        "Chef de pôle": 12,
        "Adjoint au chef de division": 12,
        "Chef de division": 13,
        "Adjoint au chef du service": 13,
        "Expert national labellisé": 13,
        "Expert international labellisé": 15,
        "RSMI": 13,
        "Chef du service": 15
    },
    "CESNAC": {
        "Assistant de subdivision": 10,
        "Adjoint au chef de pôle": 11,
        "Chef de subdivision": 11,
        "Expert senior": 11,
        "Chef de pôle": 12,
        "Adjoint au chef de division": 12,
        "Chef de division": 13,
        "Expert national labellisé": 13,
        "Expert international labellisé": 15,
        "Ajoint au chef du centre": 13,
        "Chef du centre": 15
    },
    "CRNA/SNA": {
        "Assistant de subdivision": 10,
        "Adjoint au chef de pôle": 11,
        "Chef de la maintenance régionale": 12,
        "Chef de subdivision": 11,
        "Expert senior": 11,
        "Chef de pôle": 12,
        "Adjoint au chef de division": 12,
        "Chef de programme": 12,
        "Chef de bureau exécutif permanent": 12,
        "Chef de division": 13,
        "Expert confirmé (SNA ou org A)": 11,
        "Expert senior (SNA ou org A)": 12,
        "Assistant de subdivision (SNA siège ou org A)": 11,
        "Chef de subdivision (SNA siège ou org A)": 12,
        "Adjoint au chef de pôle (SNA siège ou org A)": 11,
        "Chef de pôle": 13,
        "Adjoint au chef du service technique (SNA ou org A)": 13,
        "Adjoint au chef du service exploitation (SNA ou org A)": 13,
        "Chef du service technique (SNA ou org A)": 14,
        "Chef du service exploitation (SNA ou org A)": 14,
        "RSMI (SNA/OI)": 12,
        "RSMI (sauf SNA/OI)": 13,
        "Adjoint au chef de centre": 14,
        "Chef de centre": 15,
        "Adjoint au chef de service Orly-aviation générale (SNA/RP)": 11,
        "Adjoint au chef de service LBG": 11,
        "Chef de subdivision (Orly/aviation générale)": 11,
        "Chef de service aviation générale (SNA/RP)": 13,
        "Chef de service LBG": 13,
        "Adjoint au chef de l'organisme de Roissy": 14,
        "chef de l'organisme d'Orly": 15,
        "Chef de l'organisme de Roissy": 15,
        "Chef du SNA/RP": 15,
        "Chef de subdivision (SNA/OI)": 11,
        "Chef de subdivision (SNA/AG)": 11,
        "Chef de centre Cayenne": 13,
        "Adjoint au chef du SNA/CE": 14,
        "Adjoint au chef du SNA/SE": 14,
        "Adjoint au chef du SNA/SSE": 14,
        "Adjoint au chef du SNA/OI": 14,
        "Chef du SNA (PF, NC)": 15,
        "Chef de subdivision (B ou C) : 11,
        "Chef de division (B ou C)": 12,
        "Chef d'organisme B ou C": 13,
        "Adjoint au chef d'organisme (D ou E)": 11,
        "Chef d'organisme (D ou E)": 12
    },
    "DSAC": {
        "Assistant de subdivision": 10,
        "Chargé d'études": 10,
        "Chargé d'affaires": 11,
        "Chargé de projet": 11,
        "Coordonnateur formation": 2,
        "Chef de subdivision": 12,
        "Adjoint au chef de division": 12,
        "Chef de division": 13,
        "Chef de projet": 12,
        "Chef de programme": 12,
        "Expert national labellisé": 13,
        "Expert international labellisé": 15,
        "Adjoint au chef de pôle": 13,
        "Adjoint au chef MEAS": 14,
        "Chef de pôle": 14,
        "Responsable qualité PPO": 14,
        "Directeur du cabinet": 15,
        "Adjoint au directeur technique": 15,
        "Adjoint au DGR": 15,
        "Chef de mission": 15
    },
    "DSAC/IR": {
        "Chef de subdivision (délégation A)": 11,
        "Chef de division en délégation": 12,
        "Adjoint au délégué": 12,
        "Délégué territorial": 14,
        "Référent territorial": 14,
        "Assistant de subdivision": 11,
        "Chargé d'études": 10,
        "Chargé d'affaires": 11,
        "Chef de subdivision": 12,
        "Adjoint au chef de division": 12,
        "Chef de programme": 12,
        "Chef de cabinet": 13,
        "Chef de division": 13,
        "Expert national labellisé": 13,
        "Chef de la mission Aéroport/Grand Ouest": 13,
        "Responsable qualité PPO/PSE": 13,
        "Chef de département": 14,
        "Chef de la division TA (DSAC/N/CDG)": 14,
        "Adjoint au directeur": 14,
        "Directeur": 15
    },
    "ENAC": {
        "Enseignant": 10,
        "Assistant de subdivision": 11,
        "Enseignant confirmé": 11,
        "Enseignant senior": 12,
        "Chef de subdivision": 12,
        "Inspecteur des études": 12,
        "Responsable d'axe de recherche": 12,
        "Chef de programme": 12,
        "Adjoint au chef de division": 12,
        "Chef de pôle": 13,
        "Chef de division": 13,
        "Chef de centre": 13,
        "Expert national labellisé": 13,
        "Expert international labellisé": 15,
        "Adjoint au chef de département": 13,
        "Chef de laboratoire de recherche": 13,
        "Chef de département": 14,
        "Directeur de cabinet": 14,
        "Adjoint au secrétaire général": 14,
        "Adjoint au directeur de la formation au pilotage et des vols": 14,
        "Secrétaire général": 15,
        "Directeur adjoint": 15,
        "Directeur des études et de la recherche": 15,
        "Directeur de la formation au pilotage et des vols": 15,
        "Directeur de l'international et du développement": 15
    },
    "DSI": {
        "Chef de subdivision": 11,
        "Chef de projet": 12,
        "Chargé de projet": 11,
        "Chef de programme": 12,
        "Adjoint au chef de division": 12,
        "Chef de pôle": 13,
        "Adjoint au chef de domaine": 13,
        "Chef de domaine": 14,
        "Chef de division": 13,
        "Adjoint au DSI": 14,
        "Chef de la DSI": 15
    },
    "SEAC/DAC-NC": {
        "Assistant de subdivision": 11,
        "Chef de subdivision": 12,
        "Adjoint au chef de division": 12,
        "Chef de division": 13,
        "Chef de la division transport aérien (SEAC/PF)": 13,
        "Chef de la division contrôle technique (SEAC/PF)":13,
        "Chef du SNA SEAC/PF": 14,
        "Directeur du SEAC/PF": 15,
        "Chef du service sécurité (DAC/NC)": 13,
        "Chef du SNA DAC/NC": 14,
        "Directeur de la DAC/NC": 15,
        "Chef du DSNA/SPM": 13,
        "Directeur du SEAC/WF": 13
    },
    "Cabinet DGAC": {
        "Conseiller technique": 13
    },
    "SNIA": {
        "Adjoint au chef de département": 13,
        "Adjoint au chef d'antenne": 13,
        "Chargé de mission conseil technique et défense": 13,
        "Chargé de mission QMM": 13,
        "Chargé de mission COM": 13,
        "Chargé de mission DD": 13,
        "Secrétaire général": 14,
        "Chef de département": 14,
        "Chef d'antenne Atlantique": 14,
        "Chef d'antenne Méditerranée": 14,
        "Directeur adjoint": 15
    }
};

var fonctions_rsi = {
    "BEA": {
        "Enquêteur": 2,
        "Enquêteur senior": 3,
        "Enquêteur expérimenté": 4,
        "Chef de division": 4,
        "Chef de département": 5,
        "Enquêteur expérimenté sénior": 5,
        "Adjoint au directeur": 6,
        "Secrétaire général": 6,
        "Directeur d'enquête": 6
    },
    "DTA": {
        "Chargé d'études": 1,
        "Chargé d'affaires": 2,
        "Chef de programme": 3,
        "Adjoint au chef de bureau": 3,
        "Chef de division (DTA/MCU)": 4,
        "Adjoint au chef de pôle Ciel Unique (DTA/MCU)": 4,
        "Chef de projet construction aéronautique (DTA/SDC)": 4,
        "Adjoint au chef de la MALGH": 5,
        "Chef de bureau": 5,        
        "Chef de pôle Ciel Unique (DTA/MCU)": 5,
        "Adjoint au sous-directeur": 6,
        "Adjoint au chef de mission": 6,
    },
    "STAC": {
        "Chargé d'études": 1,
        "Assistant de subdivision": 1,
        "Chargé d'affaires": 2,
        "Chef de programme": 3,    
        "Chef de subdivision": 3,
        "Chef de division": 4,
        "Chef de département": 5
    },
    "SG": {
        "Chargé d'études": 1,
        "Chargé d'affaires": 2,
        "Chargé de projet": 2,    
        "Chef de programme": 3,
        "Adjoint au chef de bureau": 3,
        "Chef de bureau": 5,   
        "Adjoint au sous-directeur SIM": 5,
        "Conseiller mobilité carrière (SG/SDP)": 5,
        "Chef du SGTA": 6,
        "Correspondant du corps des IEEAC": 6,
        "Conseiller du secrétaire général": 6,
        "Chef de mission (SG/SDP)": 6
    },
    "DSNA/EC": {
        "Chargé d'études": 1,
        "Chargé d'affaires": 2,
        "Chargé de projet": 2,
        "Chef de programme": 3,
        "Adjoint au chef de département": 4,
        "Adjoint au chef de mission": 4,
        "Chef de division": 4,
        "Chef de département": 5,
        "Directeur de programme": 6,
        "Chef de mission": 6,
        "Directeur de cabinet": 6
    },
    "DO/EC": {
        "Assistant de subdivision": 1,
        "Chargé de projet": 2,
        "Chef de subdivision": 3,
        "Chef de programme": 3,
        "Chargé de mission": 4,
        "Chef de division": 4,
        "Chef de département": 5,
        "Adjoint au chef de département": 4,
        "RSMI" : 5,
        "Secrétaire général": 6
    },
    "DTI": {
        "Expert": 1,
        "Expert confirmé": 2,
        "Expert senior": 3,
        "Chef de projet": 3,
        "Chargé de communication": 3,
        "Coordonnateur formation": 3,
        "Coordonnateur de site": 4,
        "Expert senior chargé d'un projet majeur": 4,
        "Chef du SMQS": 4,
        "Adjoint au chef de pôle":3,
        "Adjoint au chef du pôle consolidation des exigences opérationnelles": 4,
        "Adjoint au chef du pôle exigences systèmes et architecture": 4,
        "Adjoint au chef du pôle vol et information générale": 4,
        "Adjoint au chef du pôle outils du contrôleur et surveillance": 4,
        "Adjoint au chef du pôle communication vocale et liaisons de données air-sol": 4,
        "Adjoint au chef du pôle capteurs de surveillance": 4,
        "Adjoint au chef du pôle infrastructure de télécommunications et réseaux": 4,
        "Adjoint au chef du pôle intégration, validation et déploiement": 4,
        "Adjoint au chef du pôle équipements techniques communes": 4,
        "Adjoint au chef du pôle installations": 4,
        "Chef de pôle": 4,
        "Chef de pôle fréquences et servitudes": 3,
        "Chef du pôle consolidation des exigences opérationnelles": 5,
        "Chef du pôle exigences systèmes et architecture": 5,
        "Chef du pôle vol et information générale": 5,
        "Chef du pôle outils du contrôleur et surveillance": 5,
        "Chef du pôle communication vocale et liaisons de données air-sol": 5,
        "Chef du pôle capteurs de surveillance": 5,
        "Chef du pôle infrastructure de télécommunications et réseaux": 5,
        "Chef du pôle intégration, validation et déploiement": 5,
        "Chef du pôle équipements techniques communes": 5,
        "Chef du pôle installations": 5,
        "Conseiller du directeur": 5,
        "Adjoint au chef de domaine": 5,
        "Chef de département": 5,
        "Chef de domaine": 6
    },
    "SIA": {
        "Assistant de subdivision": 1,
        "Chef de subdivision": 3,
        "Chef de division": 4,
        "Adjoint au chef du service": 4,
        "RSMI": 4,
        "Chef du service": 6
    },
    "CESNAC": {
        "Assistant de subdivision": 1,
        "Chef de subdivision": 3,
        "Chef de division": 4,
        "Ajoint au chef du centre": 4,
        "Chef du centre": 6
    },
    "CRNA/SNA": {
        "Assistant de subdivision": 1,
        "Chef de la maintenance régionale": 2,
        "Coordonnateur formation": 2,
        "Chef de subdivision": 3,
        "Adjoint au chef de division": 3,
        "Chef de programme": 3,
        "Chef de bureau exécutif permanent": 3,
        "Adjoint au chef du service technique (SNA ou org A)": 4,
        "Adjoint au chef du service exploitation (SNA ou org A)": 4,
        "Chef du service technique (SNA ou org A)": 5,
        "Chef du service exploitation (SNA ou org A)": 5,
        "RSMI (sauf SNA/OI)": 4,
        "Adjoint au chef de centre": 5,
        "Chef de centre": 6,
        "Adjoint au chef de service aviation générale (SNA/RP)": 2,
        "Adjoint au chef de service LBG": 2,
        "Chef de subdivision (Orly/aviation générale)": 3,
        "Chef de service aviation générale (SNA/RP)": 4,
        "Chef de service LBG": 4,
        "Adjoint au chef de l'organisme de Roissy": 5,
        "chef de l'organisme d'Orly": 6,
        "Chef de l'organisme de Roissy": 6,
        "Chef du SNA/RP": 6,
        "Chef de subdivision (SNA/OI)": 2,
        "Chef du SNA/OI": 4,
        "Chef de subdivision (SNA/AG)": 2,
        "Chef de centre Cayenne": 4,
        "Chef de la division technique (SNA/AG)": 4,
        "Chef de la division CA (SNA/AG)": 4,
        "Adjoint au chef du SNA/CE": 5,
        "Adjoint au chef du SNA/SE": 5,
        "Adjoint au chef du SNA/SSE": 5,
        "Chef du SNA (sauf OI, PF, NC)": 6,
        "Chef de subdivision (B ou C) : 2,
        "Chef de division (B ou C)": 3,
        "Chef d'organisme B ou C": 5,
       "Adjoint au chef CA (D ou E)": 1,
        "Adjoint au directeur d'aérodrome (D ou E)": 2,
        "Adjoint au chef d'organisme (D ou E)": 2,
        "Chef d'organisme (D ou E)": 3,
        "Chef CA (F ou G)": 1
    },
    "DSAC": {
        "Assistant de subdivision": 1,
        "Chargé d'études": 1,
        "Chargé d'affaires": 2,
        "Chargé de projet": 2,
        "Coordonnateur formation": 2,
        "Chef de subdivision": 3,
        "Chargé de communication": 3,
        "Chef de projet": 3,
        "Chargé de l'unité SUR/MET": 3,
        "Chef de programme": 3,
        "Adjoint au chef de pôle": 4,
        "Adjoint au chef MEAS": 4,
        "Chef de département (GSAC)": 5
        "Chef d'équipe internationale principale de certification": 5,
        "Chef de pôle": 5,
        "Responsable qualité PPO": 5,
        "Directeur du cabinet": 6,
        "Adjoint au directeur technique": 6,
        "Chef de mission": 6
    },
    "DSAC/IR": {
        "Chef de subdivision (délégation A)": 2,
        "Chef de division (délégation A)": 3,
        "Adjoint au chef de délégation A": 3,
        "Adjoint au chef de délégation B ou C": 2,
        "Chef de division (délégation Guadeloupe)": 2,
        "Adjoint au chef de délégation Corse": 3,
        "Chef de délégation Languedoc-Roussillon": 5,
        "Chef de délégation Côte d'Azur": 5,
        "Chef de délégation Corse": 5,
        "Chef de délégation Payd de la Loire": 5,
        "Chef de délégation Guadeloupe": 5,
        "Chef de délégation Picardie": 5,
        "Chef de délégation": 4,
        "Assistant de subdivision": 1,
        "Chargé d'études": 1,
        "Chargé d'affaires": 2,
        "Chef de subdivision": 3,
        "Adjoint au chef de division": 3,
        "Chef de programme": 3,
        "Chef de cabinet": 4,
        "Chef de division": 4,
        "Chef de la mission Aéroport/Grand Ouest": 4,
        "Responsable qualité PPO/PSE": 4,
        "Chef de département": 5,
        "Chef de la division TA (DSAC/N/CDG)": 5,
        "Chef du département SR (DSAC/OI)": 4,
        "Directeur DSAC/OI": 5,    
        "Adjoint au directeur (sauf DSAC/OI)": 5,
        "Directeur": 6
    },
    "ENAC": {
        "Chargé d'enseignement": 2,
        "Enseignant confirmé": 2,
        "Enseignant senior": 3,
        "Chef de subdivision": 3,
        "Inspecteur des études": 3,
        "Chef de groupe de recherche": 3,
        "Chef de programme": 3,
        "Délégué": 4,
        "Chef de pôle": 4,
        "Chef de division": 4,
        "Chef de centre": 4,
        "Adjoint au chef de département": 4,
        "Chef de laboratoire de recherche": 4,
        "Chef de département": 5,
        "Directeur de cabinet": 5,
        "Adjoint au secrétaire général": 5,
        "Adjoint au directeur de la formation au pilotage et des vols": 5,
        "Secrétaire général": 6,
        "Directeur adjoint": 6,
        "Directeur des études et de la recherche": 6,
        "Directeur de la formation au pilotage et des vols": 6,
        "Directeur de l'international et du développement": 6
    }
    "CEDRe/SSIM": {
        "Chef de subdivision": 2,
        "Chef de projet": 2,
        "Chargé de projet": 2,
        "Adjoint au chef de département": 3,
        "Chef de division": 3,
        "Chef de département": 5,
        "Chef du centre": 6
    },
    "SEAC": {
        "Chef de division": 3,
        "Chef de la division transport aérien (SEAC/PF)": 4,
        "Chef de la division contrôle technique (SEAC/PF)": 4,
        "Chef du service sécurité de l'aviation civile (SEAC/NC)": 4,
        "Chef du SAC SPM": 4,
        "Directeur du SEAC/WF": 4,
        "Chef du SNA SEAC/NC": 4,
        "Chef du SNA SEAC/PF": 5,
        "Directeur du SEAC/NC": 6,
        "Directeur du SEAC/PF": 6
    },
    "Cabinet DGAC": {
        "Conseiller technique": 4
    },
    "SNIA": {
        "Adjoint au chef de département": 4,
        "Adjoint au chef d'antenne": 4,
        "Chargé de mission conseil technique et défense": 4,
        "Chargé de mission QMM": 4,
        "Chargé de mission COM": 4,
        "Chargé de mission DD": 4,
        "Secrétaire général": 5,
        "Chef de département": 5,
        "Chef d'antenne Atlantique": 5,
        "Chef d'antenne Méditerranée": 5,
        "Directeur adjoint": 6
    }
};
